---
title: "automate_creation_of_name.txt"
output: html_document
date: '2023-10-17'
---

#Rscript -e "rmarkdown::render('automate_creation_of_name.txt.Rmd')"

## library
```{r}
library(dplyr)
```




## get the fastq file
```{bash}

s3_path="seqwell-fastq"
run_name="20231016_MiSeq-Yoda"
plate_name="ASU_Ctrl_FASTQ"
aws s3 cp s3://${s3_path}/${run_name}/${plate_name}/  fastq --recursive

```




## get the old name
```{bash}
bash get_fastq_name.sh
```




## modify old name
```{r}

df_old = readr::read_tsv("old_name")

df_old

df_old = df_old %>% 
  dplyr::mutate( sample_info = stringr::str_extract_all(old_id, "[A-Z][0-9]{2}_R[1,2]_001.fastq.gz", simplify = T)) %>% 
  dplyr::mutate( Well = stringr::str_extract_all(old_id, "[A-Z][0-9]{2}", simplify =T ))

df_old

```



## use map file to create name.txt
```{r}
## no _ in the name
plate_name = "ASU-Ctrl"
map_file = "20231016_MiSeq-Yoda_1825_SampleMap_updated.csv"


df_map = readr::read_csv(map_file)
sample_name = df_map %>% 
  dplyr::left_join( df_old, by = "Well") %>% 
  dplyr::mutate( ref = stringr::str_replace_all(Reference, ".fasta", "")) %>% 
  dplyr::mutate( new_id = paste(plate_name, ref, sample_info, sep="_")) %>% 
  dplyr::select( new_id, old_id)

readr::write_tsv( sample_name, "name.txt")

```
