---
title: "combine_blast_res"
output: html_document
date: '2023-07-27'
---


library
```{r}
library(dplyr)
```


##
```{r}

path = list.files("results/", recursive = T, include.dirs = FALSE)

df_info = data.frame( path = path, stringsAsFactors = F)
df_info_s = df_info %>% 
  dplyr::filter( grepl("blastn_metric", path)) %>% 
  tidyr::separate( path, c("query" , "subject"), sep=".blastn_metric/copy_", remove = F) %>% 
  dplyr::mutate( subject = stringr::str_replace_all(subject, ".txt", "")) %>% 
  dplyr::mutate( path = paste("results/", path, sep=""))


```



##
```{r}
read_file = function(x,y,z){
  
  file = readr::read_table( x, col_names = F)
  names(file) = c("qseqid", "sseqid", "pident", "length", "mismatch", "gapopen", "qstart", "qend", "sstart", "send", "evalue", "bitscore", "filename")
  file$qseqid = y
  file$sseqid = z
  return(file)
  
  
}
```



##
```{r}
a = df_info_s$path
b = df_info_s$query
c = df_info_s$subject
file = purrr::pmap_dfr( list(a,b,c), read_file)

head(file)

file_report = file %>% 
  tidyr::nest( -c(qseqid, sseqid)) %>% 
  dplyr::mutate( data2 = purrr::map(.$data, function(x){
    
    x = x %>% 
      dplyr::arrange( -length)
    x = x[1, ]
    return(x)
  })) %>% 
  dplyr::select( qseqid, sseqid, data2) %>% 
  tidyr::unnest() %>% 
  dplyr::filter( ! qseqid  == sseqid )
file_report

readr::write_csv( file_report, "pairwise_blast_for_20_plasmid.csv")
```



##
```{r}

file_report_1 = file_report %>% 
  dplyr::select(qseqid, sseqid, length) %>% 
  tidyr::spread( sseqid, length)

readr::write_csv( file_report_1, "outputs/20_plasmids_matched_seq_length.csv")


file_report_2 = file_report %>% 
  dplyr::select(qseqid, sseqid, pident) %>% 
  tidyr::spread( sseqid, pident)

readr::write_csv( file_report_2, "outputs/20_plasmids_matched_identity.csv")


```
